// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzdJFx-Oru_tktWRsJYxdaDn9kaTN1Uc',
    appId: '1:66611254261:web:b94a2085a5ad6fd5e346bc',
    messagingSenderId: '66611254261',
    projectId: 'marketview-by-clearview',
    authDomain: 'marketview-by-clearview.firebaseapp.com',
    storageBucket: 'marketview-by-clearview.firebasestorage.app',
    measurementId: 'G-9CQE1SG5GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhzmIO26Rlu9zDPsAyW5nknWUnB-hnzbY',
    appId: '1:66611254261:android:c63a5116dd98111be346bc',
    messagingSenderId: '66611254261',
    projectId: 'marketview-by-clearview',
    storageBucket: 'marketview-by-clearview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C0VOGrKidR3kZe4CFbBiXXpg4j5n_YE',
    appId: '1:66611254261:ios:a347361b0000686ce346bc',
    messagingSenderId: '66611254261',
    projectId: 'marketview-by-clearview',
    storageBucket: 'marketview-by-clearview.firebasestorage.app',
    iosClientId: '66611254261-2ob425b49upgv78u01itoi4keersb6nn.apps.googleusercontent.com',
    iosBundleId: 'com.clearviewdev.marketview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2C0VOGrKidR3kZe4CFbBiXXpg4j5n_YE',
    appId: '1:66611254261:ios:a347361b0000686ce346bc',
    messagingSenderId: '66611254261',
    projectId: 'marketview-by-clearview',
    storageBucket: 'marketview-by-clearview.firebasestorage.app',
    iosClientId: '66611254261-2ob425b49upgv78u01itoi4keersb6nn.apps.googleusercontent.com',
    iosBundleId: 'com.clearviewdev.marketview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQzdJFx-Oru_tktWRsJYxdaDn9kaTN1Uc',
    appId: '1:66611254261:web:44b25bbc2d5232f2e346bc',
    messagingSenderId: '66611254261',
    projectId: 'marketview-by-clearview',
    authDomain: 'marketview-by-clearview.firebaseapp.com',
    storageBucket: 'marketview-by-clearview.firebasestorage.app',
    measurementId: 'G-2W62CZNPBK',
  );
}
